// Code generated by gogen. DO NOT EDIT.
package dbmqapi

import (
	"strings"

	"github.com/gin-gonic/gin"
	"github.com/spf13/cast"
)

// ================ swaggen ================

func NewClusterAPIWrap(inner ClusterAPI, handler ClusterAPIHandler) *ClusterAPIWrap {
	return &ClusterAPIWrap{
		inner:   inner,
		handler: handler,
	}
}

func NewConsumerGroupAPIWrap(inner ConsumerGroupAPI, handler ConsumerGroupAPIHandler) *ConsumerGroupAPIWrap {
	return &ConsumerGroupAPIWrap{
		inner:   inner,
		handler: handler,
	}
}

func NewDBMQAPIWrap(inner DBMQAPI, handler DBMQAPIHandler) *DBMQAPIWrap {
	return &DBMQAPIWrap{
		inner:   inner,
		handler: handler,
	}
}

func NewDashboardAPIWrap(inner DashboardAPI, handler DashboardAPIHandler) *DashboardAPIWrap {
	return &DashboardAPIWrap{
		inner:   inner,
		handler: handler,
	}
}

func NewHealthAPIWrap(inner HealthAPI, handler HealthAPIHandler) *HealthAPIWrap {
	return &HealthAPIWrap{
		inner:   inner,
		handler: handler,
	}
}

func NewManualAssignmentAPIWrap(inner ManualAssignmentAPI, handler ManualAssignmentAPIHandler) *ManualAssignmentAPIWrap {
	return &ManualAssignmentAPIWrap{
		inner:   inner,
		handler: handler,
	}
}

func NewTopicAPIWrap(inner TopicAPI, handler TopicAPIHandler) *TopicAPIWrap {
	return &TopicAPIWrap{
		inner:   inner,
		handler: handler,
	}
}

func NewTopicProxyAPIWrap(inner TopicProxyAPI, handler TopicProxyAPIHandler) *TopicProxyAPIWrap {
	return &TopicProxyAPIWrap{
		inner:   inner,
		handler: handler,
	}
}

type ClusterAPIHandler interface {
	PreHandlers() []gin.HandlerFunc
}

type ConsumerGroupAPIHandler interface {
	PreHandlers() []gin.HandlerFunc
}

type DBMQAPIHandler interface {
	PreHandlers() []gin.HandlerFunc
}

type DashboardAPIHandler interface {
	PreHandlers() []gin.HandlerFunc
}

type HealthAPIHandler interface {
	PreHandlers() []gin.HandlerFunc
}

type ManualAssignmentAPIHandler interface {
	PreHandlers() []gin.HandlerFunc
}

type TopicAPIHandler interface {
	PreHandlers() []gin.HandlerFunc
}

type TopicProxyAPIHandler interface {
	PreHandlers() []gin.HandlerFunc
}

type ClusterAPIWrap struct {
	inner   ClusterAPI
	handler ClusterAPIHandler
}

func (a *ClusterAPIWrap) bind(router gin.IRoutes, method, path string, preHandlers, innerHandlers []gin.HandlerFunc, f gin.HandlerFunc) {
	var basePath string
	if v, ok := router.(interface {
		BasePath() string
	}); ok {
		basePath = v.BasePath()
	}
	handlers := make([]gin.HandlerFunc, 0, len(preHandlers)+len(innerHandlers)+1)
	handlers = append(handlers, preHandlers...)
	handlers = append(handlers, innerHandlers...)
	handlers = append(handlers, f)
	router.Handle(method, strings.TrimPrefix(path, basePath), handlers...)
}

// List
// @Summary 获取集群列表
// @Tags Cluster
// @Produce json
// @Success 200 {object} []ClusterResp
// @Router /api/v1/clusters/ [get]
func (a *ClusterAPIWrap) List(ctx *gin.Context) {
	result, err := a.inner.List(ctx.Request.Context())
	onGinResponse[[]ClusterResp](ctx, result, err)
}

// GetMetrics
// @Summary 获取集群指标
// @Tags Cluster
// @Produce json
// @Param clusterId path string true "clusterId"
// @Success 200 {object} ClusterMetricsResp
// @Router /api/v1/clusters/{clusterId}/metrics [get]
func (a *ClusterAPIWrap) GetMetrics(ctx *gin.Context) {
	clusterId := ctx.Param("clusterId")
	result, err := a.inner.GetMetrics(ctx.Request.Context(), clusterId)
	onGinResponse[ClusterMetricsResp](ctx, result, err)
}

// GetBrokers
// @Summary 获取 Broker 列表
// @Tags Cluster
// @Produce json
// @Param clusterId path string true "clusterId"
// @Success 200 {object} []BrokerResp
// @Router /api/v1/clusters/{clusterId}/brokers [get]
func (a *ClusterAPIWrap) GetBrokers(ctx *gin.Context) {
	clusterId := ctx.Param("clusterId")
	result, err := a.inner.GetBrokers(ctx.Request.Context(), clusterId)
	onGinResponse[[]BrokerResp](ctx, result, err)
}

func (a *ClusterAPIWrap) BindList(router gin.IRoutes, preHandlers ...gin.HandlerFunc) {
	var handlers []gin.HandlerFunc
	if a.handler != nil {
		handlers = append(handlers, a.handler.PreHandlers()...)
	}
	a.bind(router, "GET", "/api/v1/clusters/", preHandlers, handlers, a.List)
}

func (a *ClusterAPIWrap) BindGetMetrics(router gin.IRoutes, preHandlers ...gin.HandlerFunc) {
	var handlers []gin.HandlerFunc
	if a.handler != nil {
		handlers = append(handlers, a.handler.PreHandlers()...)
	}
	a.bind(router, "GET", "/api/v1/clusters/:clusterId/metrics", preHandlers, handlers, a.GetMetrics)
}

func (a *ClusterAPIWrap) BindGetBrokers(router gin.IRoutes, preHandlers ...gin.HandlerFunc) {
	var handlers []gin.HandlerFunc
	if a.handler != nil {
		handlers = append(handlers, a.handler.PreHandlers()...)
	}
	a.bind(router, "GET", "/api/v1/clusters/:clusterId/brokers", preHandlers, handlers, a.GetBrokers)
}

func (a *ClusterAPIWrap) BindAll(router gin.IRoutes, preHandlers ...gin.HandlerFunc) {
	a.BindList(router, preHandlers...)
	a.BindGetMetrics(router, preHandlers...)
	a.BindGetBrokers(router, preHandlers...)
}

type ConsumerGroupAPIWrap struct {
	inner   ConsumerGroupAPI
	handler ConsumerGroupAPIHandler
}

func (a *ConsumerGroupAPIWrap) bind(router gin.IRoutes, method, path string, preHandlers, innerHandlers []gin.HandlerFunc, f gin.HandlerFunc) {
	var basePath string
	if v, ok := router.(interface {
		BasePath() string
	}); ok {
		basePath = v.BasePath()
	}
	handlers := make([]gin.HandlerFunc, 0, len(preHandlers)+len(innerHandlers)+1)
	handlers = append(handlers, preHandlers...)
	handlers = append(handlers, innerHandlers...)
	handlers = append(handlers, f)
	router.Handle(method, strings.TrimPrefix(path, basePath), handlers...)
}

// List
// @Summary 获取消费组列表
// @Tags Consumer-Group
// @Produce json
// @Success 200 {object} []ConsumerGroupResp
// @Router /api/v1/consumer-groups/ [get]
func (a *ConsumerGroupAPIWrap) List(ctx *gin.Context) {
	result, err := a.inner.List(ctx.Request.Context())
	onGinResponse[[]ConsumerGroupResp](ctx, result, err)
}

// Get
// @Summary 获取单个消费组
// @Tags Consumer-Group
// @Produce json
// @Param groupId path string true "groupId"
// @Success 200 {object} ConsumerGroupResp
// @Router /api/v1/consumer-groups/{groupId} [get]
func (a *ConsumerGroupAPIWrap) Get(ctx *gin.Context) {
	groupId := ctx.Param("groupId")
	result, err := a.inner.Get(ctx.Request.Context(), groupId)
	onGinResponse[ConsumerGroupResp](ctx, result, err)
}

func (a *ConsumerGroupAPIWrap) BindList(router gin.IRoutes, preHandlers ...gin.HandlerFunc) {
	var handlers []gin.HandlerFunc
	if a.handler != nil {
		handlers = append(handlers, a.handler.PreHandlers()...)
	}
	a.bind(router, "GET", "/api/v1/consumer-groups/", preHandlers, handlers, a.List)
}

func (a *ConsumerGroupAPIWrap) BindGet(router gin.IRoutes, preHandlers ...gin.HandlerFunc) {
	var handlers []gin.HandlerFunc
	if a.handler != nil {
		handlers = append(handlers, a.handler.PreHandlers()...)
	}
	a.bind(router, "GET", "/api/v1/consumer-groups/:groupId", preHandlers, handlers, a.Get)
}

func (a *ConsumerGroupAPIWrap) BindAll(router gin.IRoutes, preHandlers ...gin.HandlerFunc) {
	a.BindList(router, preHandlers...)
	a.BindGet(router, preHandlers...)
}

type DBMQAPIWrap struct {
	inner   DBMQAPI
	handler DBMQAPIHandler
}

func (a *DBMQAPIWrap) bind(router gin.IRoutes, method, path string, preHandlers, innerHandlers []gin.HandlerFunc, f gin.HandlerFunc) {
	var basePath string
	if v, ok := router.(interface {
		BasePath() string
	}); ok {
		basePath = v.BasePath()
	}
	handlers := make([]gin.HandlerFunc, 0, len(preHandlers)+len(innerHandlers)+1)
	handlers = append(handlers, preHandlers...)
	handlers = append(handlers, innerHandlers...)
	handlers = append(handlers, f)
	router.Handle(method, strings.TrimPrefix(path, basePath), handlers...)
}

// GetStats
// @Summary 获取统计信息
// @Tags DBMQ
// @Produce json
// @Success 200 {object} DBMQStatsResp
// @Router /api/v1/dbmq/stats [get]
func (a *DBMQAPIWrap) GetStats(ctx *gin.Context) {
	result, err := a.inner.GetStats(ctx.Request.Context())
	onGinResponse[DBMQStatsResp](ctx, result, err)
}

// GetTopicMessages
// @Summary 获取 Topic 消息列表
// @Tags DBMQ
// @Produce json
// @Param topicName path string true "topicName"
// @Param req query GetTopicMessagesReq true "req"
// @Success 200 {object} TopicMessagesResp
// @Router /api/v1/dbmq/topics/{topicName}/messages [get]
func (a *DBMQAPIWrap) GetTopicMessages(ctx *gin.Context) {
	topicName := ctx.Param("topicName")
	var req GetTopicMessagesReq
	if !onGinBind(ctx, &req, "QUERY") {
		return
	}
	result, err := a.inner.GetTopicMessages(ctx.Request.Context(), topicName, req)
	onGinResponse[TopicMessagesResp](ctx, result, err)
}

// GetPartitionStats
// @Summary 获取分区统计信息
// @Tags DBMQ
// @Produce json
// @Param topicName path string true "topicName"
// @Param partitionId path integer true "partitionId"
// @Success 200 {object} PartitionStats
// @Router /api/v1/dbmq/topics/{topicName}/partitions/{partitionId}/stats [get]
func (a *DBMQAPIWrap) GetPartitionStats(ctx *gin.Context) {
	topicName := ctx.Param("topicName")
	partitionId := cast.ToUint(ctx.Param("partitionId"))
	result, err := a.inner.GetPartitionStats(ctx.Request.Context(), topicName, partitionId)
	onGinResponse[PartitionStats](ctx, result, err)
}

// GetConsumerGroupExtended
// @Summary 获取消费组扩展信息
// @Tags DBMQ
// @Produce json
// @Param groupId path string true "groupId"
// @Success 200 {object} ConsumerGroupExtendedResp
// @Router /api/v1/dbmq/consumer-groups/{groupId}/extended [get]
func (a *DBMQAPIWrap) GetConsumerGroupExtended(ctx *gin.Context) {
	groupId := ctx.Param("groupId")
	result, err := a.inner.GetConsumerGroupExtended(ctx.Request.Context(), groupId)
	onGinResponse[ConsumerGroupExtendedResp](ctx, result, err)
}

func (a *DBMQAPIWrap) BindGetStats(router gin.IRoutes, preHandlers ...gin.HandlerFunc) {
	var handlers []gin.HandlerFunc
	if a.handler != nil {
		handlers = append(handlers, a.handler.PreHandlers()...)
	}
	a.bind(router, "GET", "/api/v1/dbmq/stats", preHandlers, handlers, a.GetStats)
}

func (a *DBMQAPIWrap) BindGetTopicMessages(router gin.IRoutes, preHandlers ...gin.HandlerFunc) {
	var handlers []gin.HandlerFunc
	if a.handler != nil {
		handlers = append(handlers, a.handler.PreHandlers()...)
	}
	a.bind(router, "GET", "/api/v1/dbmq/topics/:topicName/messages", preHandlers, handlers, a.GetTopicMessages)
}

func (a *DBMQAPIWrap) BindGetPartitionStats(router gin.IRoutes, preHandlers ...gin.HandlerFunc) {
	var handlers []gin.HandlerFunc
	if a.handler != nil {
		handlers = append(handlers, a.handler.PreHandlers()...)
	}
	a.bind(router, "GET", "/api/v1/dbmq/topics/:topicName/partitions/:partitionId/stats", preHandlers, handlers, a.GetPartitionStats)
}

func (a *DBMQAPIWrap) BindGetConsumerGroupExtended(router gin.IRoutes, preHandlers ...gin.HandlerFunc) {
	var handlers []gin.HandlerFunc
	if a.handler != nil {
		handlers = append(handlers, a.handler.PreHandlers()...)
	}
	a.bind(router, "GET", "/api/v1/dbmq/consumer-groups/:groupId/extended", preHandlers, handlers, a.GetConsumerGroupExtended)
}

func (a *DBMQAPIWrap) BindAll(router gin.IRoutes, preHandlers ...gin.HandlerFunc) {
	a.BindGetStats(router, preHandlers...)
	a.BindGetTopicMessages(router, preHandlers...)
	a.BindGetPartitionStats(router, preHandlers...)
	a.BindGetConsumerGroupExtended(router, preHandlers...)
}

type DashboardAPIWrap struct {
	inner   DashboardAPI
	handler DashboardAPIHandler
}

func (a *DashboardAPIWrap) bind(router gin.IRoutes, method, path string, preHandlers, innerHandlers []gin.HandlerFunc, f gin.HandlerFunc) {
	var basePath string
	if v, ok := router.(interface {
		BasePath() string
	}); ok {
		basePath = v.BasePath()
	}
	handlers := make([]gin.HandlerFunc, 0, len(preHandlers)+len(innerHandlers)+1)
	handlers = append(handlers, preHandlers...)
	handlers = append(handlers, innerHandlers...)
	handlers = append(handlers, f)
	router.Handle(method, strings.TrimPrefix(path, basePath), handlers...)
}

// GetDashboardData
// @Summary 获取仪表板数据
// @Tags Dashboard
// @Produce json
// @Success 200 {object} DashboardDataResp
// @Router /api/v1/dashboard/data [get]
func (a *DashboardAPIWrap) GetDashboardData(ctx *gin.Context) {
	result, err := a.inner.GetDashboardData(ctx.Request.Context())
	onGinResponse[DashboardDataResp](ctx, result, err)
}

func (a *DashboardAPIWrap) BindGetDashboardData(router gin.IRoutes, preHandlers ...gin.HandlerFunc) {
	var handlers []gin.HandlerFunc
	if a.handler != nil {
		handlers = append(handlers, a.handler.PreHandlers()...)
	}
	a.bind(router, "GET", "/api/v1/dashboard/data", preHandlers, handlers, a.GetDashboardData)
}

func (a *DashboardAPIWrap) BindAll(router gin.IRoutes, preHandlers ...gin.HandlerFunc) {
	a.BindGetDashboardData(router, preHandlers...)
}

type HealthAPIWrap struct {
	inner   HealthAPI
	handler HealthAPIHandler
}

func (a *HealthAPIWrap) bind(router gin.IRoutes, method, path string, preHandlers, innerHandlers []gin.HandlerFunc, f gin.HandlerFunc) {
	var basePath string
	if v, ok := router.(interface {
		BasePath() string
	}); ok {
		basePath = v.BasePath()
	}
	handlers := make([]gin.HandlerFunc, 0, len(preHandlers)+len(innerHandlers)+1)
	handlers = append(handlers, preHandlers...)
	handlers = append(handlers, innerHandlers...)
	handlers = append(handlers, f)
	router.Handle(method, strings.TrimPrefix(path, basePath), handlers...)
}

// Health
// @Summary 健康检查
// @Tags Health
// @Produce json
// @Success 200 {object} HealthResp
// @Router /api/v1/health [get]
func (a *HealthAPIWrap) Health(ctx *gin.Context) {
	result, err := a.inner.Health(ctx.Request.Context())
	onGinResponse[HealthResp](ctx, result, err)
}

// ActuatorHealth
// @Summary Spring Boot 兼容健康检查
// @Tags Health
// @Produce json
// @Success 200 {object} HealthResp
// @Router /api/v1/actuator/health [get]
func (a *HealthAPIWrap) ActuatorHealth(ctx *gin.Context) {
	result, err := a.inner.ActuatorHealth(ctx.Request.Context())
	onGinResponse[HealthResp](ctx, result, err)
}

// ActuatorInfo
// @Summary Spring Boot 兼容信息接口
// @Tags Health
// @Produce json
// @Success 200 {object} InfoResp
// @Router /api/v1/actuator/info [get]
func (a *HealthAPIWrap) ActuatorInfo(ctx *gin.Context) {
	result, err := a.inner.ActuatorInfo(ctx.Request.Context())
	onGinResponse[InfoResp](ctx, result, err)
}

func (a *HealthAPIWrap) BindHealth(router gin.IRoutes, preHandlers ...gin.HandlerFunc) {
	var handlers []gin.HandlerFunc
	if a.handler != nil {
		handlers = append(handlers, a.handler.PreHandlers()...)
	}
	a.bind(router, "GET", "/api/v1/health", preHandlers, handlers, a.Health)
}

func (a *HealthAPIWrap) BindActuatorHealth(router gin.IRoutes, preHandlers ...gin.HandlerFunc) {
	var handlers []gin.HandlerFunc
	if a.handler != nil {
		handlers = append(handlers, a.handler.PreHandlers()...)
	}
	a.bind(router, "GET", "/api/v1/actuator/health", preHandlers, handlers, a.ActuatorHealth)
}

func (a *HealthAPIWrap) BindActuatorInfo(router gin.IRoutes, preHandlers ...gin.HandlerFunc) {
	var handlers []gin.HandlerFunc
	if a.handler != nil {
		handlers = append(handlers, a.handler.PreHandlers()...)
	}
	a.bind(router, "GET", "/api/v1/actuator/info", preHandlers, handlers, a.ActuatorInfo)
}

func (a *HealthAPIWrap) BindAll(router gin.IRoutes, preHandlers ...gin.HandlerFunc) {
	a.BindHealth(router, preHandlers...)
	a.BindActuatorHealth(router, preHandlers...)
	a.BindActuatorInfo(router, preHandlers...)
}

type ManualAssignmentAPIWrap struct {
	inner   ManualAssignmentAPI
	handler ManualAssignmentAPIHandler
}

func (a *ManualAssignmentAPIWrap) bind(router gin.IRoutes, method, path string, preHandlers, innerHandlers []gin.HandlerFunc, f gin.HandlerFunc) {
	var basePath string
	if v, ok := router.(interface {
		BasePath() string
	}); ok {
		basePath = v.BasePath()
	}
	handlers := make([]gin.HandlerFunc, 0, len(preHandlers)+len(innerHandlers)+1)
	handlers = append(handlers, preHandlers...)
	handlers = append(handlers, innerHandlers...)
	handlers = append(handlers, f)
	router.Handle(method, strings.TrimPrefix(path, basePath), handlers...)
}

// Create
// @Summary 创建手动分区分配
// @Tags Manual-Assignment
// @Accept json
// @Produce json
// @Param req body CreateManualAssignmentReq true "req"
// @Success 200 {object} ManualAssignmentResp
// @Router /api/v1/manual-assignments/ [post]
func (a *ManualAssignmentAPIWrap) Create(ctx *gin.Context) {
	var req CreateManualAssignmentReq
	if !onGinBind(ctx, &req, "JSON") {
		return
	}
	result, err := a.inner.Create(ctx.Request.Context(), req)
	onGinResponse[ManualAssignmentResp](ctx, result, err)
}

// List
// @Summary 查询手动分区分配列表
// @Tags Manual-Assignment
// @Produce json
// @Param req query ListManualAssignmentsReq true "req"
// @Success 200 {object} []ManualAssignmentResp
// @Router /api/v1/manual-assignments/ [get]
func (a *ManualAssignmentAPIWrap) List(ctx *gin.Context) {
	var req ListManualAssignmentsReq
	if !onGinBind(ctx, &req, "QUERY") {
		return
	}
	result, err := a.inner.List(ctx.Request.Context(), req)
	onGinResponse[[]ManualAssignmentResp](ctx, result, err)
}

// Delete
// @Summary 删除手动分区分配
// @Tags Manual-Assignment
// @Accept json
// @Produce json
// @Param id path integer true "id"
// @Success 200 {object} MessageResp
// @Router /api/v1/manual-assignments/{id} [delete]
func (a *ManualAssignmentAPIWrap) Delete(ctx *gin.Context) {
	id := cast.ToInt64(ctx.Param("id"))
	result, err := a.inner.Delete(ctx.Request.Context(), id)
	onGinResponse[MessageResp](ctx, result, err)
}

func (a *ManualAssignmentAPIWrap) BindCreate(router gin.IRoutes, preHandlers ...gin.HandlerFunc) {
	var handlers []gin.HandlerFunc
	if a.handler != nil {
		handlers = append(handlers, a.handler.PreHandlers()...)
	}
	a.bind(router, "POST", "/api/v1/manual-assignments/", preHandlers, handlers, a.Create)
}

func (a *ManualAssignmentAPIWrap) BindList(router gin.IRoutes, preHandlers ...gin.HandlerFunc) {
	var handlers []gin.HandlerFunc
	if a.handler != nil {
		handlers = append(handlers, a.handler.PreHandlers()...)
	}
	a.bind(router, "GET", "/api/v1/manual-assignments/", preHandlers, handlers, a.List)
}

func (a *ManualAssignmentAPIWrap) BindDelete(router gin.IRoutes, preHandlers ...gin.HandlerFunc) {
	var handlers []gin.HandlerFunc
	if a.handler != nil {
		handlers = append(handlers, a.handler.PreHandlers()...)
	}
	a.bind(router, "DELETE", "/api/v1/manual-assignments/:id", preHandlers, handlers, a.Delete)
}

func (a *ManualAssignmentAPIWrap) BindAll(router gin.IRoutes, preHandlers ...gin.HandlerFunc) {
	a.BindCreate(router, preHandlers...)
	a.BindList(router, preHandlers...)
	a.BindDelete(router, preHandlers...)
}

type TopicAPIWrap struct {
	inner   TopicAPI
	handler TopicAPIHandler
}

func (a *TopicAPIWrap) bind(router gin.IRoutes, method, path string, preHandlers, innerHandlers []gin.HandlerFunc, f gin.HandlerFunc) {
	var basePath string
	if v, ok := router.(interface {
		BasePath() string
	}); ok {
		basePath = v.BasePath()
	}
	handlers := make([]gin.HandlerFunc, 0, len(preHandlers)+len(innerHandlers)+1)
	handlers = append(handlers, preHandlers...)
	handlers = append(handlers, innerHandlers...)
	handlers = append(handlers, f)
	router.Handle(method, strings.TrimPrefix(path, basePath), handlers...)
}

// List
// @Summary 获取 Topic 列表
// @Tags Topic
// @Produce json
// @Param req query GetTopicsReq true "req"
// @Success 200 {object} []TopicResp
// @Router /api/v1/topics/ [get]
func (a *TopicAPIWrap) List(ctx *gin.Context) {
	var req GetTopicsReq
	if !onGinBind(ctx, &req, "QUERY") {
		return
	}
	result, err := a.inner.List(ctx.Request.Context(), req)
	onGinResponse[[]TopicResp](ctx, result, err)
}

// Get
// @Summary 获取单个 Topic
// @Tags Topic
// @Produce json
// @Param topicName path string true "topicName"
// @Success 200 {object} TopicResp
// @Router /api/v1/topics/{topicName} [get]
func (a *TopicAPIWrap) Get(ctx *gin.Context) {
	topicName := ctx.Param("topicName")
	result, err := a.inner.Get(ctx.Request.Context(), topicName)
	onGinResponse[TopicResp](ctx, result, err)
}

// Create
// @Summary 创建 Topic
// @Tags Topic
// @Accept json
// @Produce json
// @Param req body CreateTopicReq true "req"
// @Success 200 {object} MessageResp
// @Router /api/v1/topics/ [post]
func (a *TopicAPIWrap) Create(ctx *gin.Context) {
	var req CreateTopicReq
	if !onGinBind(ctx, &req, "JSON") {
		return
	}
	result, err := a.inner.Create(ctx.Request.Context(), req)
	onGinResponse[MessageResp](ctx, result, err)
}

// Delete
// @Summary 删除 Topic
// @Tags Topic
// @Accept json
// @Produce json
// @Param topicName path string true "topicName"
// @Success 200 {object} MessageResp
// @Router /api/v1/topics/{topicName} [delete]
func (a *TopicAPIWrap) Delete(ctx *gin.Context) {
	topicName := ctx.Param("topicName")
	result, err := a.inner.Delete(ctx.Request.Context(), topicName)
	onGinResponse[MessageResp](ctx, result, err)
}

// GetMetrics
// @Summary 获取 Topic 指标
// @Tags Topic
// @Produce json
// @Param topicName path string true "topicName"
// @Success 200 {object} TopicResp
// @Router /api/v1/topics/{topicName}/metrics [get]
func (a *TopicAPIWrap) GetMetrics(ctx *gin.Context) {
	topicName := ctx.Param("topicName")
	result, err := a.inner.GetMetrics(ctx.Request.Context(), topicName)
	onGinResponse[TopicResp](ctx, result, err)
}

func (a *TopicAPIWrap) BindList(router gin.IRoutes, preHandlers ...gin.HandlerFunc) {
	var handlers []gin.HandlerFunc
	if a.handler != nil {
		handlers = append(handlers, a.handler.PreHandlers()...)
	}
	a.bind(router, "GET", "/api/v1/topics/", preHandlers, handlers, a.List)
}

func (a *TopicAPIWrap) BindGet(router gin.IRoutes, preHandlers ...gin.HandlerFunc) {
	var handlers []gin.HandlerFunc
	if a.handler != nil {
		handlers = append(handlers, a.handler.PreHandlers()...)
	}
	a.bind(router, "GET", "/api/v1/topics/:topicName", preHandlers, handlers, a.Get)
}

func (a *TopicAPIWrap) BindCreate(router gin.IRoutes, preHandlers ...gin.HandlerFunc) {
	var handlers []gin.HandlerFunc
	if a.handler != nil {
		handlers = append(handlers, a.handler.PreHandlers()...)
	}
	a.bind(router, "POST", "/api/v1/topics/", preHandlers, handlers, a.Create)
}

func (a *TopicAPIWrap) BindDelete(router gin.IRoutes, preHandlers ...gin.HandlerFunc) {
	var handlers []gin.HandlerFunc
	if a.handler != nil {
		handlers = append(handlers, a.handler.PreHandlers()...)
	}
	a.bind(router, "DELETE", "/api/v1/topics/:topicName", preHandlers, handlers, a.Delete)
}

func (a *TopicAPIWrap) BindGetMetrics(router gin.IRoutes, preHandlers ...gin.HandlerFunc) {
	var handlers []gin.HandlerFunc
	if a.handler != nil {
		handlers = append(handlers, a.handler.PreHandlers()...)
	}
	a.bind(router, "GET", "/api/v1/topics/:topicName/metrics", preHandlers, handlers, a.GetMetrics)
}

func (a *TopicAPIWrap) BindAll(router gin.IRoutes, preHandlers ...gin.HandlerFunc) {
	a.BindList(router, preHandlers...)
	a.BindGet(router, preHandlers...)
	a.BindCreate(router, preHandlers...)
	a.BindDelete(router, preHandlers...)
	a.BindGetMetrics(router, preHandlers...)
}

type TopicProxyAPIWrap struct {
	inner   TopicProxyAPI
	handler TopicProxyAPIHandler
}

func (a *TopicProxyAPIWrap) bind(router gin.IRoutes, method, path string, preHandlers, innerHandlers []gin.HandlerFunc, f gin.HandlerFunc) {
	var basePath string
	if v, ok := router.(interface {
		BasePath() string
	}); ok {
		basePath = v.BasePath()
	}
	handlers := make([]gin.HandlerFunc, 0, len(preHandlers)+len(innerHandlers)+1)
	handlers = append(handlers, preHandlers...)
	handlers = append(handlers, innerHandlers...)
	handlers = append(handlers, f)
	router.Handle(method, strings.TrimPrefix(path, basePath), handlers...)
}

// ListTopics
// @Summary 获取 Topic 列表
// @Tags Topic-Proxy
// @Produce json
// @Success 200 {object} []string
// @Router /api/v1/topics [get]
func (a *TopicProxyAPIWrap) ListTopics(ctx *gin.Context) {
	result, err := a.inner.ListTopics(ctx.Request.Context())
	onGinResponse[[]string](ctx, result, err)
}

// GetTopicInfo
// @Summary 获取 Topic 信息
// @Tags Topic-Proxy
// @Produce json
// @Param topicName path string true "topicName"
// @Success 200 {object} TopicResp
// @Router /api/v1/topics/{topicName} [get]
func (a *TopicProxyAPIWrap) GetTopicInfo(ctx *gin.Context) {
	topicName := ctx.Param("topicName")
	result, err := a.inner.GetTopicInfo(ctx.Request.Context(), topicName)
	onGinResponse[TopicResp](ctx, result, err)
}

// GetPartitions
// @Summary 获取分区信息
// @Tags Topic-Proxy
// @Produce json
// @Param topicName path string true "topicName"
// @Success 200 {object} []PartitionStats
// @Router /api/v1/topics/{topicName}/partitions [get]
func (a *TopicProxyAPIWrap) GetPartitions(ctx *gin.Context) {
	topicName := ctx.Param("topicName")
	result, err := a.inner.GetPartitions(ctx.Request.Context(), topicName)
	onGinResponse[[]PartitionStats](ctx, result, err)
}

// ListBrokers
// @Summary 获取 Broker 列表
// @Tags Topic-Proxy
// @Produce json
// @Success 200 {object} []BrokerResp
// @Router /api/v1/brokers [get]
func (a *TopicProxyAPIWrap) ListBrokers(ctx *gin.Context) {
	result, err := a.inner.ListBrokers(ctx.Request.Context())
	onGinResponse[[]BrokerResp](ctx, result, err)
}

func (a *TopicProxyAPIWrap) BindListTopics(router gin.IRoutes, preHandlers ...gin.HandlerFunc) {
	var handlers []gin.HandlerFunc
	if a.handler != nil {
		handlers = append(handlers, a.handler.PreHandlers()...)
	}
	a.bind(router, "GET", "/api/v1/topics", preHandlers, handlers, a.ListTopics)
}

func (a *TopicProxyAPIWrap) BindGetTopicInfo(router gin.IRoutes, preHandlers ...gin.HandlerFunc) {
	var handlers []gin.HandlerFunc
	if a.handler != nil {
		handlers = append(handlers, a.handler.PreHandlers()...)
	}
	a.bind(router, "GET", "/api/v1/topics/:topicName", preHandlers, handlers, a.GetTopicInfo)
}

func (a *TopicProxyAPIWrap) BindGetPartitions(router gin.IRoutes, preHandlers ...gin.HandlerFunc) {
	var handlers []gin.HandlerFunc
	if a.handler != nil {
		handlers = append(handlers, a.handler.PreHandlers()...)
	}
	a.bind(router, "GET", "/api/v1/topics/:topicName/partitions", preHandlers, handlers, a.GetPartitions)
}

func (a *TopicProxyAPIWrap) BindListBrokers(router gin.IRoutes, preHandlers ...gin.HandlerFunc) {
	var handlers []gin.HandlerFunc
	if a.handler != nil {
		handlers = append(handlers, a.handler.PreHandlers()...)
	}
	a.bind(router, "GET", "/api/v1/brokers", preHandlers, handlers, a.ListBrokers)
}

func (a *TopicProxyAPIWrap) BindAll(router gin.IRoutes, preHandlers ...gin.HandlerFunc) {
	a.BindListTopics(router, preHandlers...)
	a.BindGetTopicInfo(router, preHandlers...)
	a.BindGetPartitions(router, preHandlers...)
	a.BindListBrokers(router, preHandlers...)
}

//
//func onGinBind(c *gin.Context, val any, typ string) bool {
//    switch typ {
//    case "JSON":
//        if err := c.ShouldBindJSON(val); err != nil {
//            c.JSON(400, gin.H{"error": err.Error()})
//            return false
//        }
//    case "FORM":
//        if err := c.ShouldBind(val); err != nil {
//            c.JSON(400, gin.H{"error": err.Error()})
//            return false
//        }
//    case "QUERY":
//        if err := c.ShouldBindQuery(val); err != nil {
//            c.JSON(400, gin.H{"error": err.Error()})
//            return false
//        }
//    default:
//        if err := c.ShouldBind(val); err != nil {
//            c.JSON(400, gin.H{"error": err.Error()})
//            return false
//        }
//    }
//    return true
//}
//
//func onGinResponse[T any](c *gin.Context, data any, err error) {
//    c.JSON(200, data)
//}
//
//func onGinBindErr(c *gin.Context, err error) {
//    c.JSON(500, gin.H{"error": err.Error()})
//}
