// Code generated by gogen. DO NOT EDIT.
package dbmqapi

import (
	"strings"

	"github.com/gin-gonic/gin"
	"github.com/spf13/cast"
)

// ================ swaggen ================

func NewClusterAPIWrap(inner ClusterAPI, handler ClusterAPIHandler) *ClusterAPIWrap {
	return &ClusterAPIWrap{
		inner:   inner,
		handler: handler,
	}
}

func NewConsumerAPIWrap(inner ConsumerAPI, handler ConsumerAPIHandler) *ConsumerAPIWrap {
	return &ConsumerAPIWrap{
		inner:   inner,
		handler: handler,
	}
}

func NewConsumerGroupAPIWrap(inner ConsumerGroupAPI, handler ConsumerGroupAPIHandler) *ConsumerGroupAPIWrap {
	return &ConsumerGroupAPIWrap{
		inner:   inner,
		handler: handler,
	}
}

func NewDBMQAPIWrap(inner DBMQAPI, handler DBMQAPIHandler) *DBMQAPIWrap {
	return &DBMQAPIWrap{
		inner:   inner,
		handler: handler,
	}
}

func NewDashboardAPIWrap(inner DashboardAPI, handler DashboardAPIHandler) *DashboardAPIWrap {
	return &DashboardAPIWrap{
		inner:   inner,
		handler: handler,
	}
}

func NewHealthAPIWrap(inner HealthAPI, handler HealthAPIHandler) *HealthAPIWrap {
	return &HealthAPIWrap{
		inner:   inner,
		handler: handler,
	}
}

func NewManualAssignmentAPIWrap(inner ManualAssignmentAPI, handler ManualAssignmentAPIHandler) *ManualAssignmentAPIWrap {
	return &ManualAssignmentAPIWrap{
		inner:   inner,
		handler: handler,
	}
}

func NewTopicAPIWrap(inner TopicAPI, handler TopicAPIHandler) *TopicAPIWrap {
	return &TopicAPIWrap{
		inner:   inner,
		handler: handler,
	}
}

func NewTopicProxyAPIWrap(inner TopicProxyAPI, handler TopicProxyAPIHandler) *TopicProxyAPIWrap {
	return &TopicProxyAPIWrap{
		inner:   inner,
		handler: handler,
	}
}

type ClusterAPIHandler interface {
	PreHandlers() []gin.HandlerFunc
}

type ConsumerAPIHandler interface {
	PreHandlers() []gin.HandlerFunc
}

type ConsumerGroupAPIHandler interface {
	PreHandlers() []gin.HandlerFunc
}

type DBMQAPIHandler interface {
	PreHandlers() []gin.HandlerFunc
}

type DashboardAPIHandler interface {
	PreHandlers() []gin.HandlerFunc
}

type HealthAPIHandler interface {
	PreHandlers() []gin.HandlerFunc
}

type ManualAssignmentAPIHandler interface {
	PreHandlers() []gin.HandlerFunc
}

type TopicAPIHandler interface {
	PreHandlers() []gin.HandlerFunc
}

type TopicProxyAPIHandler interface {
	PreHandlers() []gin.HandlerFunc
}

type ClusterAPIWrap struct {
	inner   ClusterAPI
	handler ClusterAPIHandler
}

func (a *ClusterAPIWrap) bind(router gin.IRoutes, method, path string, preHandlers, innerHandlers []gin.HandlerFunc, f gin.HandlerFunc) {
	var basePath string
	if v, ok := router.(interface {
		BasePath() string
	}); ok {
		basePath = v.BasePath()
	}
	handlers := make([]gin.HandlerFunc, 0, len(preHandlers)+len(innerHandlers)+1)
	handlers = append(handlers, preHandlers...)
	handlers = append(handlers, innerHandlers...)
	handlers = append(handlers, f)
	router.Handle(method, strings.TrimPrefix(path, basePath), handlers...)
}

// List
// @Summary 获取集群列表
// @Tags Cluster
// @Produce json
// @Success 200 {object} []ClusterResp
// @Router /clusters [get]
func (a *ClusterAPIWrap) List(ctx *gin.Context) {
	result, err := a.inner.List(ctx.Request.Context())
	onGinResponse[[]ClusterResp](ctx, result, err)
}

// GetMetrics
// @Summary 获取集群指标
// @Tags Cluster
// @Produce json
// @Param clusterId path string true "clusterId"
// @Success 200 {object} ClusterMetricsResp
// @Router /clusters/{clusterId}/metrics [get]
func (a *ClusterAPIWrap) GetMetrics(ctx *gin.Context) {
	clusterId := ctx.Param("clusterId")
	result, err := a.inner.GetMetrics(ctx.Request.Context(), clusterId)
	onGinResponse[ClusterMetricsResp](ctx, result, err)
}

// GetBrokers
// @Summary 获取 Broker 列表
// @Tags Cluster
// @Produce json
// @Param clusterId path string true "clusterId"
// @Success 200 {object} []BrokerResp
// @Router /clusters/{clusterId}/brokers [get]
func (a *ClusterAPIWrap) GetBrokers(ctx *gin.Context) {
	clusterId := ctx.Param("clusterId")
	result, err := a.inner.GetBrokers(ctx.Request.Context(), clusterId)
	onGinResponse[[]BrokerResp](ctx, result, err)
}

func (a *ClusterAPIWrap) BindList(router gin.IRoutes, preHandlers ...gin.HandlerFunc) {
	var handlers = []gin.HandlerFunc{
		func(c *gin.Context) {
			c.Set("gormgen:methodcomment", "// List 获取集群列表\n// @GET(/)")
			c.Set("gormgen:interfacecomment", "// ClusterAPI 集群管理 API\n// @TAG(Cluster)\n// @PREFIX(/clusters)")
		},
	}
	if a.handler != nil {
		handlers = append(handlers, a.handler.PreHandlers()...)
	}
	a.bind(router, "GET", "/clusters", preHandlers, handlers, a.List)
}

func (a *ClusterAPIWrap) BindGetMetrics(router gin.IRoutes, preHandlers ...gin.HandlerFunc) {
	var handlers = []gin.HandlerFunc{
		func(c *gin.Context) {
			c.Set("gormgen:methodcomment", "// GetMetrics 获取集群指标\n// @GET(/{clusterId}/metrics)")
			c.Set("gormgen:interfacecomment", "// ClusterAPI 集群管理 API\n// @TAG(Cluster)\n// @PREFIX(/clusters)")
		},
	}
	if a.handler != nil {
		handlers = append(handlers, a.handler.PreHandlers()...)
	}
	a.bind(router, "GET", "/clusters/:clusterId/metrics", preHandlers, handlers, a.GetMetrics)
}

func (a *ClusterAPIWrap) BindGetBrokers(router gin.IRoutes, preHandlers ...gin.HandlerFunc) {
	var handlers = []gin.HandlerFunc{
		func(c *gin.Context) {
			c.Set("gormgen:methodcomment", "// GetBrokers 获取 Broker 列表\n// @GET(/{clusterId}/brokers)")
			c.Set("gormgen:interfacecomment", "// ClusterAPI 集群管理 API\n// @TAG(Cluster)\n// @PREFIX(/clusters)")
		},
	}
	if a.handler != nil {
		handlers = append(handlers, a.handler.PreHandlers()...)
	}
	a.bind(router, "GET", "/clusters/:clusterId/brokers", preHandlers, handlers, a.GetBrokers)
}

func (a *ClusterAPIWrap) BindAll(router gin.IRoutes, preHandlers ...gin.HandlerFunc) {
	a.BindList(router, preHandlers...)
	a.BindGetMetrics(router, preHandlers...)
	a.BindGetBrokers(router, preHandlers...)
}

type ConsumerAPIWrap struct {
	inner   ConsumerAPI
	handler ConsumerAPIHandler
}

func (a *ConsumerAPIWrap) bind(router gin.IRoutes, method, path string, preHandlers, innerHandlers []gin.HandlerFunc, f gin.HandlerFunc) {
	var basePath string
	if v, ok := router.(interface {
		BasePath() string
	}); ok {
		basePath = v.BasePath()
	}
	handlers := make([]gin.HandlerFunc, 0, len(preHandlers)+len(innerHandlers)+1)
	handlers = append(handlers, preHandlers...)
	handlers = append(handlers, innerHandlers...)
	handlers = append(handlers, f)
	router.Handle(method, strings.TrimPrefix(path, basePath), handlers...)
}

// List
// @Summary 获取所有消费者
// @Tags Consumer
// @Produce json
// @Success 200 {object} []ConsumerResp
// @Router /consumers [get]
func (a *ConsumerAPIWrap) List(ctx *gin.Context) {
	result, err := a.inner.List(ctx.Request.Context())
	onGinResponse[[]ConsumerResp](ctx, result, err)
}

func (a *ConsumerAPIWrap) BindList(router gin.IRoutes, preHandlers ...gin.HandlerFunc) {
	var handlers = []gin.HandlerFunc{
		func(c *gin.Context) {
			c.Set("gormgen:methodcomment", "// List 获取所有消费者\n// @GET(/)")
			c.Set("gormgen:interfacecomment", "// ConsumerAPI 消费者 API\n// @TAG(Consumer)\n// @PREFIX(/consumers)")
		},
	}
	if a.handler != nil {
		handlers = append(handlers, a.handler.PreHandlers()...)
	}
	a.bind(router, "GET", "/consumers", preHandlers, handlers, a.List)
}

func (a *ConsumerAPIWrap) BindAll(router gin.IRoutes, preHandlers ...gin.HandlerFunc) {
	a.BindList(router, preHandlers...)
}

type ConsumerGroupAPIWrap struct {
	inner   ConsumerGroupAPI
	handler ConsumerGroupAPIHandler
}

func (a *ConsumerGroupAPIWrap) bind(router gin.IRoutes, method, path string, preHandlers, innerHandlers []gin.HandlerFunc, f gin.HandlerFunc) {
	var basePath string
	if v, ok := router.(interface {
		BasePath() string
	}); ok {
		basePath = v.BasePath()
	}
	handlers := make([]gin.HandlerFunc, 0, len(preHandlers)+len(innerHandlers)+1)
	handlers = append(handlers, preHandlers...)
	handlers = append(handlers, innerHandlers...)
	handlers = append(handlers, f)
	router.Handle(method, strings.TrimPrefix(path, basePath), handlers...)
}

// List
// @Summary 获取消费组列表
// @Tags Consumer-Group
// @Produce json
// @Success 200 {object} []ConsumerGroupResp
// @Router /consumer-groups [get]
func (a *ConsumerGroupAPIWrap) List(ctx *gin.Context) {
	result, err := a.inner.List(ctx.Request.Context())
	onGinResponse[[]ConsumerGroupResp](ctx, result, err)
}

// ListStaleProgress
// @Summary 获取消费严重滞后的进度列表
// @Tags Consumer-Group
// @Produce json
// @Param req query ListStaleProgressReq true "req"
// @Success 200 {object} []StaleProgressResp
// @Router /consumer-groups/stale-progress [get]
func (a *ConsumerGroupAPIWrap) ListStaleProgress(ctx *gin.Context) {
	var req ListStaleProgressReq
	if !onGinBind(ctx, &req, "QUERY") {
		return
	}
	result, err := a.inner.ListStaleProgress(ctx.Request.Context(), req)
	onGinResponse[[]StaleProgressResp](ctx, result, err)
}

// ListDetachedProgress
// @Summary 获取孤立残留进度列表
// @Tags Consumer-Group
// @Produce json
// @Success 200 {object} []DetachedProgressResp
// @Router /consumer-groups/detached-progress [get]
func (a *ConsumerGroupAPIWrap) ListDetachedProgress(ctx *gin.Context) {
	result, err := a.inner.ListDetachedProgress(ctx.Request.Context())
	onGinResponse[[]DetachedProgressResp](ctx, result, err)
}

// Get
// @Summary 获取单个消费组
// @Tags Consumer-Group
// @Produce json
// @Param groupId path string true "groupId"
// @Success 200 {object} ConsumerGroupResp
// @Router /consumer-groups/{groupId} [get]
func (a *ConsumerGroupAPIWrap) Get(ctx *gin.Context) {
	groupId := ctx.Param("groupId")
	result, err := a.inner.Get(ctx.Request.Context(), groupId)
	onGinResponse[ConsumerGroupResp](ctx, result, err)
}

// TriggerRebalance
// @Summary 强制触发消费组重新均衡
// @Tags Consumer-Group
// @Accept json
// @Produce json
// @Param groupId path string true "groupId"
// @Success 200 {object} MessageResp
// @Router /consumer-groups/{groupId}/rebalance [post]
func (a *ConsumerGroupAPIWrap) TriggerRebalance(ctx *gin.Context) {
	groupId := ctx.Param("groupId")
	result, err := a.inner.TriggerRebalance(ctx.Request.Context(), groupId)
	onGinResponse[MessageResp](ctx, result, err)
}

// Delete
// @Summary 删除消费组
// @Tags Consumer-Group
// @Accept json
// @Produce json
// @Param groupId path string true "groupId"
// @Success 200 {object} MessageResp
// @Router /consumer-groups/{groupId} [delete]
func (a *ConsumerGroupAPIWrap) Delete(ctx *gin.Context) {
	groupId := ctx.Param("groupId")
	result, err := a.inner.Delete(ctx.Request.Context(), groupId)
	onGinResponse[MessageResp](ctx, result, err)
}

// DeleteStaleProgress
// @Summary 删除指定消费严重滞后进度
// @Tags Consumer-Group
// @Accept json
// @Produce json
// @Param groupId path string true "groupId"
// @Param req body DeleteStaleProgressReq true "req"
// @Success 200 {object} MessageResp
// @Router /consumer-groups/{groupId}/stale-progress [delete]
func (a *ConsumerGroupAPIWrap) DeleteStaleProgress(ctx *gin.Context) {
	groupId := ctx.Param("groupId")
	var req DeleteStaleProgressReq
	if !onGinBind(ctx, &req, "JSON") {
		return
	}
	result, err := a.inner.DeleteStaleProgress(ctx.Request.Context(), groupId, req)
	onGinResponse[MessageResp](ctx, result, err)
}

// DeleteDetachedProgress
// @Summary 删除指定孤立残留进度
// @Tags Consumer-Group
// @Accept json
// @Produce json
// @Param groupId path string true "groupId"
// @Param req body DeleteDetachedProgressReq true "req"
// @Success 200 {object} MessageResp
// @Router /consumer-groups/{groupId}/detached-progress [delete]
func (a *ConsumerGroupAPIWrap) DeleteDetachedProgress(ctx *gin.Context) {
	groupId := ctx.Param("groupId")
	var req DeleteDetachedProgressReq
	if !onGinBind(ctx, &req, "JSON") {
		return
	}
	result, err := a.inner.DeleteDetachedProgress(ctx.Request.Context(), groupId, req)
	onGinResponse[MessageResp](ctx, result, err)
}

func (a *ConsumerGroupAPIWrap) BindList(router gin.IRoutes, preHandlers ...gin.HandlerFunc) {
	var handlers = []gin.HandlerFunc{
		func(c *gin.Context) {
			c.Set("gormgen:methodcomment", "// List 获取消费组列表\n// @GET(/)")
			c.Set("gormgen:interfacecomment", "// ConsumerGroupAPI 消费组管理 API\n// @TAG(Consumer-Group)\n// @PREFIX(/consumer-groups)")
		},
	}
	if a.handler != nil {
		handlers = append(handlers, a.handler.PreHandlers()...)
	}
	a.bind(router, "GET", "/consumer-groups", preHandlers, handlers, a.List)
}

func (a *ConsumerGroupAPIWrap) BindListStaleProgress(router gin.IRoutes, preHandlers ...gin.HandlerFunc) {
	var handlers = []gin.HandlerFunc{
		func(c *gin.Context) {
			c.Set("gormgen:methodcomment", "// ListStaleProgress 获取消费严重滞后的进度列表\n// @GET(/stale-progress)")
			c.Set("gormgen:interfacecomment", "// ConsumerGroupAPI 消费组管理 API\n// @TAG(Consumer-Group)\n// @PREFIX(/consumer-groups)")
		},
	}
	if a.handler != nil {
		handlers = append(handlers, a.handler.PreHandlers()...)
	}
	a.bind(router, "GET", "/consumer-groups/stale-progress", preHandlers, handlers, a.ListStaleProgress)
}

func (a *ConsumerGroupAPIWrap) BindListDetachedProgress(router gin.IRoutes, preHandlers ...gin.HandlerFunc) {
	var handlers = []gin.HandlerFunc{
		func(c *gin.Context) {
			c.Set("gormgen:methodcomment", "// ListDetachedProgress 获取孤立残留进度列表\n// @GET(/detached-progress)")
			c.Set("gormgen:interfacecomment", "// ConsumerGroupAPI 消费组管理 API\n// @TAG(Consumer-Group)\n// @PREFIX(/consumer-groups)")
		},
	}
	if a.handler != nil {
		handlers = append(handlers, a.handler.PreHandlers()...)
	}
	a.bind(router, "GET", "/consumer-groups/detached-progress", preHandlers, handlers, a.ListDetachedProgress)
}

func (a *ConsumerGroupAPIWrap) BindGet(router gin.IRoutes, preHandlers ...gin.HandlerFunc) {
	var handlers = []gin.HandlerFunc{
		func(c *gin.Context) {
			c.Set("gormgen:methodcomment", "// Get 获取单个消费组\n// @GET(/{groupId})")
			c.Set("gormgen:interfacecomment", "// ConsumerGroupAPI 消费组管理 API\n// @TAG(Consumer-Group)\n// @PREFIX(/consumer-groups)")
		},
	}
	if a.handler != nil {
		handlers = append(handlers, a.handler.PreHandlers()...)
	}
	a.bind(router, "GET", "/consumer-groups/:groupId", preHandlers, handlers, a.Get)
}

func (a *ConsumerGroupAPIWrap) BindTriggerRebalance(router gin.IRoutes, preHandlers ...gin.HandlerFunc) {
	var handlers = []gin.HandlerFunc{
		func(c *gin.Context) {
			c.Set("gormgen:methodcomment", "// TriggerRebalance 强制触发消费组重新均衡\n// @POST(/{groupId}/rebalance)")
			c.Set("gormgen:interfacecomment", "// ConsumerGroupAPI 消费组管理 API\n// @TAG(Consumer-Group)\n// @PREFIX(/consumer-groups)")
		},
	}
	if a.handler != nil {
		handlers = append(handlers, a.handler.PreHandlers()...)
	}
	a.bind(router, "POST", "/consumer-groups/:groupId/rebalance", preHandlers, handlers, a.TriggerRebalance)
}

func (a *ConsumerGroupAPIWrap) BindDelete(router gin.IRoutes, preHandlers ...gin.HandlerFunc) {
	var handlers = []gin.HandlerFunc{
		func(c *gin.Context) {
			c.Set("gormgen:methodcomment", "// Delete 删除消费组\n// @DELETE(/{groupId})")
			c.Set("gormgen:interfacecomment", "// ConsumerGroupAPI 消费组管理 API\n// @TAG(Consumer-Group)\n// @PREFIX(/consumer-groups)")
		},
	}
	if a.handler != nil {
		handlers = append(handlers, a.handler.PreHandlers()...)
	}
	a.bind(router, "DELETE", "/consumer-groups/:groupId", preHandlers, handlers, a.Delete)
}

func (a *ConsumerGroupAPIWrap) BindDeleteStaleProgress(router gin.IRoutes, preHandlers ...gin.HandlerFunc) {
	var handlers = []gin.HandlerFunc{
		func(c *gin.Context) {
			c.Set("gormgen:methodcomment", "// DeleteStaleProgress 删除指定消费严重滞后进度\n// @DELETE(/{groupId}/stale-progress)")
			c.Set("gormgen:interfacecomment", "// ConsumerGroupAPI 消费组管理 API\n// @TAG(Consumer-Group)\n// @PREFIX(/consumer-groups)")
		},
	}
	if a.handler != nil {
		handlers = append(handlers, a.handler.PreHandlers()...)
	}
	a.bind(router, "DELETE", "/consumer-groups/:groupId/stale-progress", preHandlers, handlers, a.DeleteStaleProgress)
}

func (a *ConsumerGroupAPIWrap) BindDeleteDetachedProgress(router gin.IRoutes, preHandlers ...gin.HandlerFunc) {
	var handlers = []gin.HandlerFunc{
		func(c *gin.Context) {
			c.Set("gormgen:methodcomment", "// DeleteDetachedProgress 删除指定孤立残留进度\n// @DELETE(/{groupId}/detached-progress)")
			c.Set("gormgen:interfacecomment", "// ConsumerGroupAPI 消费组管理 API\n// @TAG(Consumer-Group)\n// @PREFIX(/consumer-groups)")
		},
	}
	if a.handler != nil {
		handlers = append(handlers, a.handler.PreHandlers()...)
	}
	a.bind(router, "DELETE", "/consumer-groups/:groupId/detached-progress", preHandlers, handlers, a.DeleteDetachedProgress)
}

func (a *ConsumerGroupAPIWrap) BindAll(router gin.IRoutes, preHandlers ...gin.HandlerFunc) {
	a.BindList(router, preHandlers...)
	a.BindListStaleProgress(router, preHandlers...)
	a.BindListDetachedProgress(router, preHandlers...)
	a.BindGet(router, preHandlers...)
	a.BindTriggerRebalance(router, preHandlers...)
	a.BindDelete(router, preHandlers...)
	a.BindDeleteStaleProgress(router, preHandlers...)
	a.BindDeleteDetachedProgress(router, preHandlers...)
}

type DBMQAPIWrap struct {
	inner   DBMQAPI
	handler DBMQAPIHandler
}

func (a *DBMQAPIWrap) bind(router gin.IRoutes, method, path string, preHandlers, innerHandlers []gin.HandlerFunc, f gin.HandlerFunc) {
	var basePath string
	if v, ok := router.(interface {
		BasePath() string
	}); ok {
		basePath = v.BasePath()
	}
	handlers := make([]gin.HandlerFunc, 0, len(preHandlers)+len(innerHandlers)+1)
	handlers = append(handlers, preHandlers...)
	handlers = append(handlers, innerHandlers...)
	handlers = append(handlers, f)
	router.Handle(method, strings.TrimPrefix(path, basePath), handlers...)
}

// GetStats
// @Summary 获取统计信息
// @Tags DBMQ
// @Produce json
// @Success 200 {object} DBMQStatsResp
// @Router /stats [get]
func (a *DBMQAPIWrap) GetStats(ctx *gin.Context) {
	result, err := a.inner.GetStats(ctx.Request.Context())
	onGinResponse[DBMQStatsResp](ctx, result, err)
}

// GetTopicMessages
// @Summary 获取 Topic 消息列表
// @Tags DBMQ
// @Produce json
// @Param topicName path string true "topicName"
// @Param req query GetTopicMessagesReq true "req"
// @Success 200 {object} TopicMessagesResp
// @Router /topics/{topicName}/messages [get]
func (a *DBMQAPIWrap) GetTopicMessages(ctx *gin.Context) {
	topicName := ctx.Param("topicName")
	var req GetTopicMessagesReq
	if !onGinBind(ctx, &req, "QUERY") {
		return
	}
	result, err := a.inner.GetTopicMessages(ctx.Request.Context(), topicName, req)
	onGinResponse[TopicMessagesResp](ctx, result, err)
}

// GetPartitionStats
// @Summary 获取分区统计信息
// @Tags DBMQ
// @Produce json
// @Param topicName path string true "topicName"
// @Param partitionId path integer true "partitionId"
// @Success 200 {object} PartitionStats
// @Router /topics/{topicName}/partitions/{partitionId}/stats [get]
func (a *DBMQAPIWrap) GetPartitionStats(ctx *gin.Context) {
	topicName := ctx.Param("topicName")
	partitionId := cast.ToUint(ctx.Param("partitionId"))
	result, err := a.inner.GetPartitionStats(ctx.Request.Context(), topicName, partitionId)
	onGinResponse[PartitionStats](ctx, result, err)
}

// GetConsumerGroupExtended
// @Summary 获取消费组扩展信息
// @Tags DBMQ
// @Produce json
// @Param groupId path string true "groupId"
// @Success 200 {object} ConsumerGroupExtendedResp
// @Router /consumer-groups/{groupId}/extended [get]
func (a *DBMQAPIWrap) GetConsumerGroupExtended(ctx *gin.Context) {
	groupId := ctx.Param("groupId")
	result, err := a.inner.GetConsumerGroupExtended(ctx.Request.Context(), groupId)
	onGinResponse[ConsumerGroupExtendedResp](ctx, result, err)
}

// ResendMessages
// @Summary 重发消息
// @Tags DBMQ
// @Accept json
// @Produce json
// @Param req body ResendMessagesReq true "req"
// @Success 200 {object} ResendMessagesResp
// @Router /messages/resend [post]
func (a *DBMQAPIWrap) ResendMessages(ctx *gin.Context) {
	var req ResendMessagesReq
	if !onGinBind(ctx, &req, "JSON") {
		return
	}
	result, err := a.inner.ResendMessages(ctx.Request.Context(), req)
	onGinResponse[ResendMessagesResp](ctx, result, err)
}

func (a *DBMQAPIWrap) BindGetStats(router gin.IRoutes, preHandlers ...gin.HandlerFunc) {
	var handlers = []gin.HandlerFunc{
		func(c *gin.Context) {
			c.Set("gormgen:methodcomment", "// GetStats 获取统计信息\n// @GET(/stats)")
			c.Set("gormgen:interfacecomment", "// DBMQAPI DBMQ 专用 API\n// @TAG(DBMQ)")
		},
	}
	if a.handler != nil {
		handlers = append(handlers, a.handler.PreHandlers()...)
	}
	a.bind(router, "GET", "/stats", preHandlers, handlers, a.GetStats)
}

func (a *DBMQAPIWrap) BindGetTopicMessages(router gin.IRoutes, preHandlers ...gin.HandlerFunc) {
	var handlers = []gin.HandlerFunc{
		func(c *gin.Context) {
			c.Set("gormgen:methodcomment", "// GetTopicMessages 获取 Topic 消息列表\n// @GET(/topics/{topicName}/messages)")
			c.Set("gormgen:interfacecomment", "// DBMQAPI DBMQ 专用 API\n// @TAG(DBMQ)")
		},
	}
	if a.handler != nil {
		handlers = append(handlers, a.handler.PreHandlers()...)
	}
	a.bind(router, "GET", "/topics/:topicName/messages", preHandlers, handlers, a.GetTopicMessages)
}

func (a *DBMQAPIWrap) BindGetPartitionStats(router gin.IRoutes, preHandlers ...gin.HandlerFunc) {
	var handlers = []gin.HandlerFunc{
		func(c *gin.Context) {
			c.Set("gormgen:methodcomment", "// GetPartitionStats 获取分区统计信息\n// @GET(/topics/{topicName}/partitions/{partitionId}/stats)")
			c.Set("gormgen:interfacecomment", "// DBMQAPI DBMQ 专用 API\n// @TAG(DBMQ)")
		},
	}
	if a.handler != nil {
		handlers = append(handlers, a.handler.PreHandlers()...)
	}
	a.bind(router, "GET", "/topics/:topicName/partitions/:partitionId/stats", preHandlers, handlers, a.GetPartitionStats)
}

func (a *DBMQAPIWrap) BindGetConsumerGroupExtended(router gin.IRoutes, preHandlers ...gin.HandlerFunc) {
	var handlers = []gin.HandlerFunc{
		func(c *gin.Context) {
			c.Set("gormgen:methodcomment", "// GetConsumerGroupExtended 获取消费组扩展信息\n// @GET(/consumer-groups/{groupId}/extended)")
			c.Set("gormgen:interfacecomment", "// DBMQAPI DBMQ 专用 API\n// @TAG(DBMQ)")
		},
	}
	if a.handler != nil {
		handlers = append(handlers, a.handler.PreHandlers()...)
	}
	a.bind(router, "GET", "/consumer-groups/:groupId/extended", preHandlers, handlers, a.GetConsumerGroupExtended)
}

func (a *DBMQAPIWrap) BindResendMessages(router gin.IRoutes, preHandlers ...gin.HandlerFunc) {
	var handlers = []gin.HandlerFunc{
		func(c *gin.Context) {
			c.Set("gormgen:methodcomment", "// ResendMessages 重发消息\n// @POST(/messages/resend)")
			c.Set("gormgen:interfacecomment", "// DBMQAPI DBMQ 专用 API\n// @TAG(DBMQ)")
		},
	}
	if a.handler != nil {
		handlers = append(handlers, a.handler.PreHandlers()...)
	}
	a.bind(router, "POST", "/messages/resend", preHandlers, handlers, a.ResendMessages)
}

func (a *DBMQAPIWrap) BindAll(router gin.IRoutes, preHandlers ...gin.HandlerFunc) {
	a.BindGetStats(router, preHandlers...)
	a.BindGetTopicMessages(router, preHandlers...)
	a.BindGetPartitionStats(router, preHandlers...)
	a.BindGetConsumerGroupExtended(router, preHandlers...)
	a.BindResendMessages(router, preHandlers...)
}

type DashboardAPIWrap struct {
	inner   DashboardAPI
	handler DashboardAPIHandler
}

func (a *DashboardAPIWrap) bind(router gin.IRoutes, method, path string, preHandlers, innerHandlers []gin.HandlerFunc, f gin.HandlerFunc) {
	var basePath string
	if v, ok := router.(interface {
		BasePath() string
	}); ok {
		basePath = v.BasePath()
	}
	handlers := make([]gin.HandlerFunc, 0, len(preHandlers)+len(innerHandlers)+1)
	handlers = append(handlers, preHandlers...)
	handlers = append(handlers, innerHandlers...)
	handlers = append(handlers, f)
	router.Handle(method, strings.TrimPrefix(path, basePath), handlers...)
}

// GetDashboardData
// @Summary 获取仪表板数据
// @Tags Dashboard
// @Produce json
// @Success 200 {object} DashboardDataResp
// @Router /dashboard/data [get]
func (a *DashboardAPIWrap) GetDashboardData(ctx *gin.Context) {
	result, err := a.inner.GetDashboardData(ctx.Request.Context())
	onGinResponse[DashboardDataResp](ctx, result, err)
}

func (a *DashboardAPIWrap) BindGetDashboardData(router gin.IRoutes, preHandlers ...gin.HandlerFunc) {
	var handlers = []gin.HandlerFunc{
		func(c *gin.Context) {
			c.Set("gormgen:methodcomment", "// GetDashboardData 获取仪表板数据\n// @GET(/dashboard/data)")
			c.Set("gormgen:interfacecomment", "// DashboardAPI 仪表板 API\n// @TAG(Dashboard)")
		},
	}
	if a.handler != nil {
		handlers = append(handlers, a.handler.PreHandlers()...)
	}
	a.bind(router, "GET", "/dashboard/data", preHandlers, handlers, a.GetDashboardData)
}

func (a *DashboardAPIWrap) BindAll(router gin.IRoutes, preHandlers ...gin.HandlerFunc) {
	a.BindGetDashboardData(router, preHandlers...)
}

type HealthAPIWrap struct {
	inner   HealthAPI
	handler HealthAPIHandler
}

func (a *HealthAPIWrap) bind(router gin.IRoutes, method, path string, preHandlers, innerHandlers []gin.HandlerFunc, f gin.HandlerFunc) {
	var basePath string
	if v, ok := router.(interface {
		BasePath() string
	}); ok {
		basePath = v.BasePath()
	}
	handlers := make([]gin.HandlerFunc, 0, len(preHandlers)+len(innerHandlers)+1)
	handlers = append(handlers, preHandlers...)
	handlers = append(handlers, innerHandlers...)
	handlers = append(handlers, f)
	router.Handle(method, strings.TrimPrefix(path, basePath), handlers...)
}

// Health
// @Summary 健康检查
// @Tags Health
// @Produce json
// @Success 200 {object} HealthResp
// @Router /health [get]
func (a *HealthAPIWrap) Health(ctx *gin.Context) {
	result, err := a.inner.Health(ctx.Request.Context())
	onGinResponse[HealthResp](ctx, result, err)
}

// ActuatorHealth
// @Summary Spring Boot 兼容健康检查
// @Tags Health
// @Produce json
// @Success 200 {object} HealthResp
// @Router /actuator/health [get]
func (a *HealthAPIWrap) ActuatorHealth(ctx *gin.Context) {
	result, err := a.inner.ActuatorHealth(ctx.Request.Context())
	onGinResponse[HealthResp](ctx, result, err)
}

// ActuatorInfo
// @Summary Spring Boot 兼容信息接口
// @Tags Health
// @Produce json
// @Success 200 {object} InfoResp
// @Router /actuator/info [get]
func (a *HealthAPIWrap) ActuatorInfo(ctx *gin.Context) {
	result, err := a.inner.ActuatorInfo(ctx.Request.Context())
	onGinResponse[InfoResp](ctx, result, err)
}

func (a *HealthAPIWrap) BindHealth(router gin.IRoutes, preHandlers ...gin.HandlerFunc) {
	var handlers = []gin.HandlerFunc{
		func(c *gin.Context) {
			c.Set("gormgen:methodcomment", "// Health 健康检查\n// @GET(/health)")
			c.Set("gormgen:interfacecomment", "// HealthAPI 健康检查 API\n// @TAG(Health)")
		},
	}
	if a.handler != nil {
		handlers = append(handlers, a.handler.PreHandlers()...)
	}
	a.bind(router, "GET", "/health", preHandlers, handlers, a.Health)
}

func (a *HealthAPIWrap) BindActuatorHealth(router gin.IRoutes, preHandlers ...gin.HandlerFunc) {
	var handlers = []gin.HandlerFunc{
		func(c *gin.Context) {
			c.Set("gormgen:methodcomment", "// ActuatorHealth Spring Boot 兼容健康检查\n// @GET(/actuator/health)")
			c.Set("gormgen:interfacecomment", "// HealthAPI 健康检查 API\n// @TAG(Health)")
		},
	}
	if a.handler != nil {
		handlers = append(handlers, a.handler.PreHandlers()...)
	}
	a.bind(router, "GET", "/actuator/health", preHandlers, handlers, a.ActuatorHealth)
}

func (a *HealthAPIWrap) BindActuatorInfo(router gin.IRoutes, preHandlers ...gin.HandlerFunc) {
	var handlers = []gin.HandlerFunc{
		func(c *gin.Context) {
			c.Set("gormgen:methodcomment", "// ActuatorInfo Spring Boot 兼容信息接口\n// @GET(/actuator/info)")
			c.Set("gormgen:interfacecomment", "// HealthAPI 健康检查 API\n// @TAG(Health)")
		},
	}
	if a.handler != nil {
		handlers = append(handlers, a.handler.PreHandlers()...)
	}
	a.bind(router, "GET", "/actuator/info", preHandlers, handlers, a.ActuatorInfo)
}

func (a *HealthAPIWrap) BindAll(router gin.IRoutes, preHandlers ...gin.HandlerFunc) {
	a.BindHealth(router, preHandlers...)
	a.BindActuatorHealth(router, preHandlers...)
	a.BindActuatorInfo(router, preHandlers...)
}

type ManualAssignmentAPIWrap struct {
	inner   ManualAssignmentAPI
	handler ManualAssignmentAPIHandler
}

func (a *ManualAssignmentAPIWrap) bind(router gin.IRoutes, method, path string, preHandlers, innerHandlers []gin.HandlerFunc, f gin.HandlerFunc) {
	var basePath string
	if v, ok := router.(interface {
		BasePath() string
	}); ok {
		basePath = v.BasePath()
	}
	handlers := make([]gin.HandlerFunc, 0, len(preHandlers)+len(innerHandlers)+1)
	handlers = append(handlers, preHandlers...)
	handlers = append(handlers, innerHandlers...)
	handlers = append(handlers, f)
	router.Handle(method, strings.TrimPrefix(path, basePath), handlers...)
}

// Create
// @Summary 创建手动分区分配
// @Tags Manual-Assignment
// @Accept json
// @Produce json
// @Param req body CreateManualAssignmentReq true "req"
// @Success 200 {object} ManualAssignmentResp
// @Router /manual-assignments [post]
func (a *ManualAssignmentAPIWrap) Create(ctx *gin.Context) {
	var req CreateManualAssignmentReq
	if !onGinBind(ctx, &req, "JSON") {
		return
	}
	result, err := a.inner.Create(ctx.Request.Context(), req)
	onGinResponse[ManualAssignmentResp](ctx, result, err)
}

// List
// @Summary 查询手动分区分配列表
// @Tags Manual-Assignment
// @Produce json
// @Param req query ListManualAssignmentsReq true "req"
// @Success 200 {object} []ManualAssignmentResp
// @Router /manual-assignments [get]
func (a *ManualAssignmentAPIWrap) List(ctx *gin.Context) {
	var req ListManualAssignmentsReq
	if !onGinBind(ctx, &req, "QUERY") {
		return
	}
	result, err := a.inner.List(ctx.Request.Context(), req)
	onGinResponse[[]ManualAssignmentResp](ctx, result, err)
}

// Delete
// @Summary 删除手动分区分配
// @Tags Manual-Assignment
// @Accept json
// @Produce json
// @Param id path integer true "id"
// @Success 200 {object} MessageResp
// @Router /manual-assignments/{id} [delete]
func (a *ManualAssignmentAPIWrap) Delete(ctx *gin.Context) {
	id := cast.ToInt64(ctx.Param("id"))
	result, err := a.inner.Delete(ctx.Request.Context(), id)
	onGinResponse[MessageResp](ctx, result, err)
}

func (a *ManualAssignmentAPIWrap) BindCreate(router gin.IRoutes, preHandlers ...gin.HandlerFunc) {
	var handlers = []gin.HandlerFunc{
		func(c *gin.Context) {
			c.Set("gormgen:methodcomment", "// Create 创建手动分区分配\n// @POST(/)")
			c.Set("gormgen:interfacecomment", "// ManualAssignmentAPI 手动分区分配 API\n// @TAG(Manual-Assignment)\n// @PREFIX(/manual-assignments)")
		},
	}
	if a.handler != nil {
		handlers = append(handlers, a.handler.PreHandlers()...)
	}
	a.bind(router, "POST", "/manual-assignments", preHandlers, handlers, a.Create)
}

func (a *ManualAssignmentAPIWrap) BindList(router gin.IRoutes, preHandlers ...gin.HandlerFunc) {
	var handlers = []gin.HandlerFunc{
		func(c *gin.Context) {
			c.Set("gormgen:methodcomment", "// List 查询手动分区分配列表\n// @GET(/)")
			c.Set("gormgen:interfacecomment", "// ManualAssignmentAPI 手动分区分配 API\n// @TAG(Manual-Assignment)\n// @PREFIX(/manual-assignments)")
		},
	}
	if a.handler != nil {
		handlers = append(handlers, a.handler.PreHandlers()...)
	}
	a.bind(router, "GET", "/manual-assignments", preHandlers, handlers, a.List)
}

func (a *ManualAssignmentAPIWrap) BindDelete(router gin.IRoutes, preHandlers ...gin.HandlerFunc) {
	var handlers = []gin.HandlerFunc{
		func(c *gin.Context) {
			c.Set("gormgen:methodcomment", "// Delete 删除手动分区分配\n// @DELETE(/{id})")
			c.Set("gormgen:interfacecomment", "// ManualAssignmentAPI 手动分区分配 API\n// @TAG(Manual-Assignment)\n// @PREFIX(/manual-assignments)")
		},
	}
	if a.handler != nil {
		handlers = append(handlers, a.handler.PreHandlers()...)
	}
	a.bind(router, "DELETE", "/manual-assignments/:id", preHandlers, handlers, a.Delete)
}

func (a *ManualAssignmentAPIWrap) BindAll(router gin.IRoutes, preHandlers ...gin.HandlerFunc) {
	a.BindCreate(router, preHandlers...)
	a.BindList(router, preHandlers...)
	a.BindDelete(router, preHandlers...)
}

type TopicAPIWrap struct {
	inner   TopicAPI
	handler TopicAPIHandler
}

func (a *TopicAPIWrap) bind(router gin.IRoutes, method, path string, preHandlers, innerHandlers []gin.HandlerFunc, f gin.HandlerFunc) {
	var basePath string
	if v, ok := router.(interface {
		BasePath() string
	}); ok {
		basePath = v.BasePath()
	}
	handlers := make([]gin.HandlerFunc, 0, len(preHandlers)+len(innerHandlers)+1)
	handlers = append(handlers, preHandlers...)
	handlers = append(handlers, innerHandlers...)
	handlers = append(handlers, f)
	router.Handle(method, strings.TrimPrefix(path, basePath), handlers...)
}

// List
// @Summary 获取 Topic 列表
// @Tags Topic
// @Produce json
// @Param req query GetTopicsReq true "req"
// @Success 200 {object} []TopicResp
// @Router /topics [get]
func (a *TopicAPIWrap) List(ctx *gin.Context) {
	var req GetTopicsReq
	if !onGinBind(ctx, &req, "QUERY") {
		return
	}
	result, err := a.inner.List(ctx.Request.Context(), req)
	onGinResponse[[]TopicResp](ctx, result, err)
}

// Get
// @Summary 获取单个 Topic
// @Tags Topic
// @Produce json
// @Param topicName path string true "topicName"
// @Success 200 {object} TopicResp
// @Router /topics/{topicName} [get]
func (a *TopicAPIWrap) Get(ctx *gin.Context) {
	topicName := ctx.Param("topicName")
	result, err := a.inner.Get(ctx.Request.Context(), topicName)
	onGinResponse[TopicResp](ctx, result, err)
}

// Create
// @Summary 创建 Topic
// @Tags Topic
// @Accept json
// @Produce json
// @Param req body CreateTopicReq true "req"
// @Success 200 {object} MessageResp
// @Router /topics [post]
func (a *TopicAPIWrap) Create(ctx *gin.Context) {
	var req CreateTopicReq
	if !onGinBind(ctx, &req, "JSON") {
		return
	}
	result, err := a.inner.Create(ctx.Request.Context(), req)
	onGinResponse[MessageResp](ctx, result, err)
}

// Delete
// @Summary 删除 Topic
// @Tags Topic
// @Accept json
// @Produce json
// @Param topicName path string true "topicName"
// @Success 200 {object} MessageResp
// @Router /topics/{topicName} [delete]
func (a *TopicAPIWrap) Delete(ctx *gin.Context) {
	topicName := ctx.Param("topicName")
	result, err := a.inner.Delete(ctx.Request.Context(), topicName)
	onGinResponse[MessageResp](ctx, result, err)
}

// GetMetrics
// @Summary 获取 Topic 指标
// @Tags Topic
// @Produce json
// @Param topicName path string true "topicName"
// @Success 200 {object} TopicResp
// @Router /topics/{topicName}/metrics [get]
func (a *TopicAPIWrap) GetMetrics(ctx *gin.Context) {
	topicName := ctx.Param("topicName")
	result, err := a.inner.GetMetrics(ctx.Request.Context(), topicName)
	onGinResponse[TopicResp](ctx, result, err)
}

// ListConsumerGroups
// @Summary 获取消费此 Topic 的消费组列表
// @Tags Topic
// @Produce json
// @Param topicName path string true "topicName"
// @Success 200 {object} []ConsumerGroupResp
// @Router /topics/{topicName}/consumer-groups [get]
func (a *TopicAPIWrap) ListConsumerGroups(ctx *gin.Context) {
	topicName := ctx.Param("topicName")
	result, err := a.inner.ListConsumerGroups(ctx.Request.Context(), topicName)
	onGinResponse[[]ConsumerGroupResp](ctx, result, err)
}

func (a *TopicAPIWrap) BindList(router gin.IRoutes, preHandlers ...gin.HandlerFunc) {
	var handlers = []gin.HandlerFunc{
		func(c *gin.Context) {
			c.Set("gormgen:methodcomment", "// List 获取 Topic 列表\n// @GET(/)")
			c.Set("gormgen:interfacecomment", "// TopicAPI Topic 管理 API\n// @TAG(Topic)\n// @PREFIX(/topics)")
		},
	}
	if a.handler != nil {
		handlers = append(handlers, a.handler.PreHandlers()...)
	}
	a.bind(router, "GET", "/topics", preHandlers, handlers, a.List)
}

func (a *TopicAPIWrap) BindGet(router gin.IRoutes, preHandlers ...gin.HandlerFunc) {
	var handlers = []gin.HandlerFunc{
		func(c *gin.Context) {
			c.Set("gormgen:methodcomment", "// Get 获取单个 Topic\n// @GET(/{topicName})")
			c.Set("gormgen:interfacecomment", "// TopicAPI Topic 管理 API\n// @TAG(Topic)\n// @PREFIX(/topics)")
		},
	}
	if a.handler != nil {
		handlers = append(handlers, a.handler.PreHandlers()...)
	}
	a.bind(router, "GET", "/topics/:topicName", preHandlers, handlers, a.Get)
}

func (a *TopicAPIWrap) BindCreate(router gin.IRoutes, preHandlers ...gin.HandlerFunc) {
	var handlers = []gin.HandlerFunc{
		func(c *gin.Context) {
			c.Set("gormgen:methodcomment", "// Create 创建 Topic\n// @POST(/)")
			c.Set("gormgen:interfacecomment", "// TopicAPI Topic 管理 API\n// @TAG(Topic)\n// @PREFIX(/topics)")
		},
	}
	if a.handler != nil {
		handlers = append(handlers, a.handler.PreHandlers()...)
	}
	a.bind(router, "POST", "/topics", preHandlers, handlers, a.Create)
}

func (a *TopicAPIWrap) BindDelete(router gin.IRoutes, preHandlers ...gin.HandlerFunc) {
	var handlers = []gin.HandlerFunc{
		func(c *gin.Context) {
			c.Set("gormgen:methodcomment", "// Delete 删除 Topic\n// @DELETE(/{topicName})")
			c.Set("gormgen:interfacecomment", "// TopicAPI Topic 管理 API\n// @TAG(Topic)\n// @PREFIX(/topics)")
		},
	}
	if a.handler != nil {
		handlers = append(handlers, a.handler.PreHandlers()...)
	}
	a.bind(router, "DELETE", "/topics/:topicName", preHandlers, handlers, a.Delete)
}

func (a *TopicAPIWrap) BindGetMetrics(router gin.IRoutes, preHandlers ...gin.HandlerFunc) {
	var handlers = []gin.HandlerFunc{
		func(c *gin.Context) {
			c.Set("gormgen:methodcomment", "// GetMetrics 获取 Topic 指标\n// @GET(/{topicName}/metrics)")
			c.Set("gormgen:interfacecomment", "// TopicAPI Topic 管理 API\n// @TAG(Topic)\n// @PREFIX(/topics)")
		},
	}
	if a.handler != nil {
		handlers = append(handlers, a.handler.PreHandlers()...)
	}
	a.bind(router, "GET", "/topics/:topicName/metrics", preHandlers, handlers, a.GetMetrics)
}

func (a *TopicAPIWrap) BindListConsumerGroups(router gin.IRoutes, preHandlers ...gin.HandlerFunc) {
	var handlers = []gin.HandlerFunc{
		func(c *gin.Context) {
			c.Set("gormgen:methodcomment", "// ListConsumerGroups 获取消费此 Topic 的消费组列表\n// @GET(/{topicName}/consumer-groups)")
			c.Set("gormgen:interfacecomment", "// TopicAPI Topic 管理 API\n// @TAG(Topic)\n// @PREFIX(/topics)")
		},
	}
	if a.handler != nil {
		handlers = append(handlers, a.handler.PreHandlers()...)
	}
	a.bind(router, "GET", "/topics/:topicName/consumer-groups", preHandlers, handlers, a.ListConsumerGroups)
}

func (a *TopicAPIWrap) BindAll(router gin.IRoutes, preHandlers ...gin.HandlerFunc) {
	a.BindList(router, preHandlers...)
	a.BindGet(router, preHandlers...)
	a.BindCreate(router, preHandlers...)
	a.BindDelete(router, preHandlers...)
	a.BindGetMetrics(router, preHandlers...)
	a.BindListConsumerGroups(router, preHandlers...)
}

type TopicProxyAPIWrap struct {
	inner   TopicProxyAPI
	handler TopicProxyAPIHandler
}

func (a *TopicProxyAPIWrap) bind(router gin.IRoutes, method, path string, preHandlers, innerHandlers []gin.HandlerFunc, f gin.HandlerFunc) {
	var basePath string
	if v, ok := router.(interface {
		BasePath() string
	}); ok {
		basePath = v.BasePath()
	}
	handlers := make([]gin.HandlerFunc, 0, len(preHandlers)+len(innerHandlers)+1)
	handlers = append(handlers, preHandlers...)
	handlers = append(handlers, innerHandlers...)
	handlers = append(handlers, f)
	router.Handle(method, strings.TrimPrefix(path, basePath), handlers...)
}

// ListTopics
// @Summary 获取 Topic 列表
// @Tags Topic-Proxy
// @Produce json
// @Success 200 {object} []string
// @Router /1/topics [get]
func (a *TopicProxyAPIWrap) ListTopics(ctx *gin.Context) {
	result, err := a.inner.ListTopics(ctx.Request.Context())
	onGinResponse[[]string](ctx, result, err)
}

// GetTopicInfo
// @Summary 获取 Topic 信息
// @Tags Topic-Proxy
// @Produce json
// @Param topicName path string true "topicName"
// @Success 200 {object} TopicResp
// @Router /1/topics/{topicName} [get]
func (a *TopicProxyAPIWrap) GetTopicInfo(ctx *gin.Context) {
	topicName := ctx.Param("topicName")
	result, err := a.inner.GetTopicInfo(ctx.Request.Context(), topicName)
	onGinResponse[TopicResp](ctx, result, err)
}

// GetPartitions
// @Summary 获取分区信息
// @Tags Topic-Proxy
// @Produce json
// @Param topicName path string true "topicName"
// @Success 200 {object} []PartitionStats
// @Router /1/topics/{topicName}/partitions [get]
func (a *TopicProxyAPIWrap) GetPartitions(ctx *gin.Context) {
	topicName := ctx.Param("topicName")
	result, err := a.inner.GetPartitions(ctx.Request.Context(), topicName)
	onGinResponse[[]PartitionStats](ctx, result, err)
}

// ListBrokers
// @Summary 获取 Broker 列表
// @Tags Topic-Proxy
// @Produce json
// @Success 200 {object} []BrokerResp
// @Router /1/brokers [get]
func (a *TopicProxyAPIWrap) ListBrokers(ctx *gin.Context) {
	result, err := a.inner.ListBrokers(ctx.Request.Context())
	onGinResponse[[]BrokerResp](ctx, result, err)
}

func (a *TopicProxyAPIWrap) BindListTopics(router gin.IRoutes, preHandlers ...gin.HandlerFunc) {
	var handlers = []gin.HandlerFunc{
		func(c *gin.Context) {
			c.Set("gormgen:methodcomment", "// ListTopics 获取 Topic 列表\n// @GET(/topics)")
			c.Set("gormgen:interfacecomment", "// TopicProxyAPI Topic 代理 API（提供简化的 Topic 和 Broker 接口）\n// @TAG(Topic-Proxy)\n// @PREFIX(/1)")
		},
	}
	if a.handler != nil {
		handlers = append(handlers, a.handler.PreHandlers()...)
	}
	a.bind(router, "GET", "/1/topics", preHandlers, handlers, a.ListTopics)
}

func (a *TopicProxyAPIWrap) BindGetTopicInfo(router gin.IRoutes, preHandlers ...gin.HandlerFunc) {
	var handlers = []gin.HandlerFunc{
		func(c *gin.Context) {
			c.Set("gormgen:methodcomment", "// GetTopicInfo 获取 Topic 信息\n// @GET(/topics/{topicName})")
			c.Set("gormgen:interfacecomment", "// TopicProxyAPI Topic 代理 API（提供简化的 Topic 和 Broker 接口）\n// @TAG(Topic-Proxy)\n// @PREFIX(/1)")
		},
	}
	if a.handler != nil {
		handlers = append(handlers, a.handler.PreHandlers()...)
	}
	a.bind(router, "GET", "/1/topics/:topicName", preHandlers, handlers, a.GetTopicInfo)
}

func (a *TopicProxyAPIWrap) BindGetPartitions(router gin.IRoutes, preHandlers ...gin.HandlerFunc) {
	var handlers = []gin.HandlerFunc{
		func(c *gin.Context) {
			c.Set("gormgen:methodcomment", "// GetPartitions 获取分区信息\n// @GET(/topics/{topicName}/partitions)")
			c.Set("gormgen:interfacecomment", "// TopicProxyAPI Topic 代理 API（提供简化的 Topic 和 Broker 接口）\n// @TAG(Topic-Proxy)\n// @PREFIX(/1)")
		},
	}
	if a.handler != nil {
		handlers = append(handlers, a.handler.PreHandlers()...)
	}
	a.bind(router, "GET", "/1/topics/:topicName/partitions", preHandlers, handlers, a.GetPartitions)
}

func (a *TopicProxyAPIWrap) BindListBrokers(router gin.IRoutes, preHandlers ...gin.HandlerFunc) {
	var handlers = []gin.HandlerFunc{
		func(c *gin.Context) {
			c.Set("gormgen:methodcomment", "// ListBrokers 获取 Broker 列表\n// @GET(/brokers)")
			c.Set("gormgen:interfacecomment", "// TopicProxyAPI Topic 代理 API（提供简化的 Topic 和 Broker 接口）\n// @TAG(Topic-Proxy)\n// @PREFIX(/1)")
		},
	}
	if a.handler != nil {
		handlers = append(handlers, a.handler.PreHandlers()...)
	}
	a.bind(router, "GET", "/1/brokers", preHandlers, handlers, a.ListBrokers)
}

func (a *TopicProxyAPIWrap) BindAll(router gin.IRoutes, preHandlers ...gin.HandlerFunc) {
	a.BindListTopics(router, preHandlers...)
	a.BindGetTopicInfo(router, preHandlers...)
	a.BindGetPartitions(router, preHandlers...)
	a.BindListBrokers(router, preHandlers...)
}

//
//func onGinBind(c *gin.Context, val any, typ string) bool {
//    switch typ {
//    case "JSON":
//        if err := c.ShouldBindJSON(val); err != nil {
//            c.JSON(400, gin.H{"error": err.Error()})
//            return false
//        }
//    case "FORM":
//        if err := c.ShouldBind(val); err != nil {
//            c.JSON(400, gin.H{"error": err.Error()})
//            return false
//        }
//    case "QUERY":
//        if err := c.ShouldBindQuery(val); err != nil {
//            c.JSON(400, gin.H{"error": err.Error()})
//            return false
//        }
//    default:
//        if err := c.ShouldBind(val); err != nil {
//            c.JSON(400, gin.H{"error": err.Error()})
//            return false
//        }
//    }
//    return true
//}
//
//func onGinResponse[T any](c *gin.Context, data any, err error) {
//    c.JSON(200, data)
//}
//
//func onGinBindErr(c *gin.Context, err error) {
//    c.JSON(500, gin.H{"error": err.Error()})
//}
